#!/bin/bash
if [[ "$#" -ge "1" ]]; then
  targetBranch=$1
  currentBranch=$(git branch --show-current)
  git branch "$currentBranch"_back
  git reset --hard $targetBranch
  git merge --no-edit --squash "$currentBranch"_back
  git commit --no-edit
  git branch -D "$currentBranch"_back
else
  echo "specify target branch or commit hash"
fi